export const GET_SONGS_REQUEST = "GET_SONGS_REQUEST";
export const SONG_REQUEST_SUCCESS = "SONG_REQUEST_SUCCESS";
export const SONG_REQUEST_FAILURE = "SONG_REQUEST_FAILURE";
export const INIT_SONGS = "INIT_SONGS";

